M48
; DRILL file {KiCad 7.0.1} date Mon Sep 18 10:08:39 2023
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-09-18T10:08:39+03:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.1
; #@! TF.FileFunction,Plated,1,2,PTH
FMAT,2
INCH
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T1C0.0354
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T2C0.0433
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T3C0.0472
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T4C0.0591
%
G90
G05
T1
X7.05Y-1.35
X7.15Y-1.35
T2
X7.472Y-1.3614
X7.472Y-1.5386
X7.728Y-1.3614
X7.728Y-1.5386
T3
X6.7Y-1.35
X6.7Y-1.85
T4
X6.6933Y-2.4
X7.5Y-2.4
T0
M30
